name: Build with Gradle
on:
  push:
    branches:
      - master
      - develop
      
permissions:
  contents: write
  security-events: write
  
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Run tests
        run: ./gradlew test
        
      - name: Generate HTML test report
        run: ./gradlew jacocoTestReport
        
      - name: Archive HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: test/reports
          
      - name: Download Test Results
        uses: actions/download-artifact@v2
        with:
          name: Test Report
          path: test/reports
